### PR TITLE
Changed minAIFabricVersion onto v22.4 for TMAnalyzerModel

### PR DESCRIPTION
**Pull request by nkwayer**
- Changed the manifest file for v1.1.6 of the TM package to be available only for v22.4

### CODE REVIEW

**Review by mka-rainmaker — APPROVED** [review]

**Comment by aakashuipath** [comment]
@vivekjhauipath , can you please confirm.

**Review by vivekjhauipath — CHANGES_REQUESTED** [review]
Remove v, only `22.4`
cc @mohitseth-nitrr

**Review by mohitseth-nitrr — APPROVED** [review]
LGTM

**Comment by nkwayer** [comment]
> Remove v, only `22.4` cc @mohitseth-nitrr

Done @vivekjhauipath

**Review by vivekjhauipath — APPROVED** [review]
LGTM

**Pull request merged**
