### PR TITLE
Add metadata for 21.10.10 models

### PR DESCRIPTION
**Pull request by irinel-birsan-uipath**

### CODE REVIEW

**Comment by irinel-birsan-uipath** [comment]
This has to be merged after CU release.

**Review by vnaren23 — DISMISSED** [review]
LGTM

**Review by mohitseth-nitrr — APPROVED** [review]
LGTM

**Review by mohitseth-nitrr — APPROVED** [review]
LGTM

**Review by vnaren23 — APPROVED** [review]

**Pull request merged**
