### PR TITLE
[AIFBR-6874] Add changes to make orchestrator name lower case

### PR DESCRIPTION
**Pull request by aniket202**

### CODE REVIEW

**Review by mohitseth-nitrr — APPROVED** [review]
lgtm

**Review by rajivml — APPROVED** [review]
lgtm

**Comment by rajivml** [comment]
@mohitseth-nitrr @aniket202  do we have to do similar change while taking input from config screen as well ? like what ever user input from config screen convert the same to lower case

**Comment by rajivml** [comment]
> @mohitseth-nitrr @aniket202 do we have to do similar change while taking input from config screen as well ? like what ever user input from config screen convert the same to lower case

have seen that other PR just now...cool...ignore this comment

**Pull request merged**
