### PR TITLE
Release merge

### PR DESCRIPTION
**Pull request by irinel-birsan-uipath**
Issue: AIFBR-8881

### CODE REVIEW

**Review by mohitseth-nitrr — APPROVED** [review]
LGTM

**Comment by mohitseth-nitrr** [comment]
As discussed over slack, this PR can only be merged after corresponding changes are released for on-premise build.

**Review by SahilChaudhary25 — CHANGES_REQUESTED** [review]
This PR will wait untill we have database entries in pkg manager service related to Language version 2 fpr PYTHON37_DU

**Review by SahilChaudhary25 — APPROVED** [review]
LGTM @irinel-birsan-uipath We can merge once verification is completed

**Pull request merged**
