### PR TITLE
Change ai fabric name to ai center in oob metadata files

### PR DESCRIPTION
**Pull request by aniket202**

### CODE REVIEW

**Review by vivekjhauipath — COMMENTED** [review]
LGTM. But do it in metadats files too

**Comment by aniket202** [comment]
@vivekjhauipath done. these are the only references I could fine. Rest are in the url or db name which we are not changing

**Review by vivekjhauipath — APPROVED** [review]
LGTM

**Review by mohitseth-nitrr — APPROVED** [review]
LGTM

**Pull request merged**
