### PR TITLE
Update version number for 22.10 for CV 

### PR DESCRIPTION
**Pull request by mihairaduvlad**
Update the versioning schema also, in order to match with actual CV versioning schema and decreasing the chances of adding a wrong version number

### CODE REVIEW

**Review by irinel-birsan-uipath — APPROVED** [review]

**Review by vnaren23 — COMMENTED** [review]
Since version 9 has already been released, we should create a new file, not edit version 9. 

Also @vivekjhauipath do you know if we can add the version as part of the file name?

**Comment by vivekjhauipath** [comment]
> Since version 9 has already been released, we should create a new file, not edit version 9.
> 
> Also @vivekjhauipath do you know if we can add the version as part of the file name?

Yes, please don't change the version of existing.
Also, version should match fileName. To customers customVersion will be visible, why not change that?

**Comment by vnaren23** [comment]
> > > Since version 9 has already been released, we should create a new file, not edit version 9.
> > > Also @vivekjhauipath do you know if we can add the version as part of the file name?
> > 
> > 
> > Yes, please don't change the version of existing. Also, version should match fileName. To customers customVersion will be visible, why not change that?
> 
> This is pushed only in testing branch. We want to change the versioning schema for computer-vision, and version number to be equal with cv model version, so in the future will be less chance of confussion for us. Why can't I change the version number and fileName number in testing branch?

@mihairaduvlad There is logic built on top of the number and fileName. We have a customVersion field which serves this purpose. However it'll need to follow sem versioning like [here](https://github.com/UiPath/ai-customer-scripts/blob/stable/metadata/ComputerVision__9__metadata.json#L23)

**Comment by mihairaduvlad** [comment]
> Since version 9 has already been released, we should create a new file, not edit version 9.
> 
> Also @vivekjhauipath do you know if we can add the version as part of the file name?

I've created a new file called metadata/ComputerVision__22100701__metadata.json and deleted the version 9 file.

**Comment by mihairaduvlad** [comment]
> > > > Since version 9 has already been released, we should create a new file, not edit version 9.
> > > > Also @vivekjhauipath do you know if we can add the version as part of the file name?
> > > 
> > > 
> > > Yes, please don't change the version of existing. Also, version should match fileName. To customers customVersion will be visible, why not change that?
> > 
> > 
> > This is pushed only in testing branch. We want to change the versioning schema for computer-vision, and version number to be equal with cv model version, so in the future will be less chance of confussion for us. Why can't I change the version number and fileName number in testing branch?
> 
> @mihairaduvlad There is logic built on top of the number and fileName. We have a customVersion field which serves this purpose. However it'll need to follow sem versioning like [here](https://github.com/UiPath/ai-customer-scripts/blob/stable/metadata/ComputerVision__9__metadata.json#L23)

I understand this, but if fileName number and version number matches, why can't I change the fileName in 22100701 and version in 22100701, as I did in this PR?

**Comment by vnaren23** [comment]
Approving only for testing. Lets not remove version 9 from stable branch even if this works.

**Review by vnaren23 — APPROVED** [review]

**Pull request merged**
