### PR TITLE
🍒 Deprecate IFE, FE, IKC

### PR DESCRIPTION
**Pull request by irinel-birsan-uipath**

### CODE REVIEW

**Review by vnaren23 — DISMISSED** [review]
LGTM

**Review by mohitseth-nitrr — DISMISSED** [review]
LGTM

**Review by vivekjhauipath — APPROVED** [review]
LGTM.

Though be aware that this will only reflect for new customers? Can't we remove these files in that case?

**Comment by irinel-birsan-uipath** [comment]
> LGTM.
> 
> Though be aware that this will only reflect for new customers? Can't we remove these files in that case?

We need to keep them for a period until we remove them completely.

Yes. We are aware that this is reflecting only for new customers.

**Review by sstefanov78 — APPROVED** [review]

**Pull request merged**
