### PR TITLE
Fix JapaneseInvoices file name and update change log

### PR DESCRIPTION
**Pull request by irinel-birsan-uipath**
Fix JapaneseInvoices filename which contains an unexpected space at the end.

Update the change log to reflect the last used model versions.

### CODE REVIEW

**Review by mohitseth-nitrr — APPROVED** [review]
LGTM

**Review by vivekjhauipath — APPROVED** [review]
LGTM but why did we need to change model names

**Comment by florin-szilagyi** [comment]
where si the "fix japaneseinvoice filename" fix? I only see version increment

**Comment by irinel-birsan-uipath** [comment]
> where si the "fix japaneseinvoice filename" fix? I only see version increment

It is a sneaky space in the file name.

image

**Comment by irinel-birsan-uipath** [comment]
> LGTM but why did we need to change model names

Actually, it is a filename fix, because of the extra space that was left in there in the initial commit.

**Pull request merged**
